# =========================================================
# ELASTICSEARCH CONFIGURATION
# SOC-IAC PLATFORM
# =========================================================

# =========================================================
# CLUSTER
# =========================================================
cluster.name: soc-cluster

node.name: soc-elasticsearch-node

network.host: 0.0.0.0
http.port: 9200

discovery.type: single-node

xpack.security.enabled: false
