# =========================================================
# LOGSTASH CONFIGURATION
# SOC-IAC PLATFORM
# =========================================================

# =========================================================
# NODE
# =========================================================

node.name: soc-logstash

# =========================================================
# NETWORK
# =========================================================

http.host: "0.0.0.0"

# =========================================================
# PIPELINE
# =========================================================

path.config: /usr/share/logstash/pipeline

# =========================================================
# DATA PATH
# =========================================================

path.data: /usr/share/logstash/data

# =========================================================
# LOGS
# =========================================================

path.logs: /usr/share/logstash/logs

# =========================================================
# PIPELINE PERFORMANCE
# =========================================================

pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# =========================================================
# DEAD LETTER QUEUE
# =========================================================

dead_letter_queue.enable: true

# =========================================================
# MONITORING
# =========================================================

xpack.monitoring.enabled: false

# =========================================================
# CONFIG RELOAD
# =========================================================

config.reload.automatic: true
config.reload.interval: 5s

# =========================================================
# LOGGING
# =========================================================

log.level: info

# =========================================================
# API
# =========================================================

api.enabled: true

# =========================================================
# QUEUE
# =========================================================

queue.type: memory

# =========================================================
# ECS COMPATIBILITY
# =========================================================

pipeline.ecs_compatibility: disabled

# =========================================================
# SHUTDOWN
# =========================================================

pipeline.unsafe_shutdown: true